#!/bin/bash
# Script to check for Autoppia Discord updates and announcements
# This helps monitor for important changes or updates

echo "🔍 Checking Autoppia Resources for Updates"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "📚 Official Resources:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Official Documentation:"
echo "   ${BLUE}https://luxit.gitbook.io/autoppia-docs${NC}"
echo ""
echo "2. Miner Deployment Guide:"
echo "   ${BLUE}https://deepwiki.com/autoppia/autoppia_web_agents_subnet/6.3-miner-deployment${NC}"
echo ""
echo "3. Communication Protocol:"
echo "   ${BLUE}https://deepwiki.com/autoppia/autoppia_web_agents_subnet/4-communication-protocol${NC}"
echo ""
echo "4. Official Discord:"
echo "   ${BLUE}https://discord.gg/autoppia${NC}"
echo "   ${YELLOW}⚠️  Join Discord to check #miners channel for latest updates${NC}"
echo ""
echo "5. GitHub Repositories:"
echo "   ${BLUE}https://github.com/autoppia/autoppia_web_agents_subnet${NC}"
echo "   ${BLUE}https://github.com/autoppia/autoppia_iwa${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 What to Check:"
echo ""
echo "1. ${GREEN}GitHub Repos${NC}:"
echo "   - Check for recent commits/changes"
echo "   - Look for synapse type definitions in protocol.py"
echo "   - Review miner examples for patterns"
echo ""
echo "2. ${GREEN}Discord${NC}:"
echo "   - #miners channel for announcements"
echo "   - #support channel for issues"
echo "   - Check pinned messages"
echo ""
echo "3. ${GREEN}Documentation${NC}:"
echo "   - Review deployment guide updates"
echo "   - Check communication protocol changes"
echo "   - Verify configuration requirements"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 Quick Links:"
echo ""
echo "Open in browser:"
echo "  xdg-open https://luxit.gitbook.io/autoppia-docs 2>/dev/null || open https://luxit.gitbook.io/autoppia-docs 2>/dev/null || echo 'Open manually: https://luxit.gitbook.io/autoppia-docs'"
echo "  xdg-open https://github.com/autoppia/autoppia_web_agents_subnet 2>/dev/null || open https://github.com/autoppia/autoppia_web_agents_subnet 2>/dev/null || echo 'Open manually: https://github.com/autoppia/autoppia_web_agents_subnet'"
echo "  xdg-open https://discord.gg/autoppia 2>/dev/null || open https://discord.gg/autoppia 2>/dev/null || echo 'Open manually: https://discord.gg/autoppia'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Tips:"
echo "  - Check GitHub for 'protocol.py' or 'synapse.py' files"
echo "  - Look for 'StartRoundSynapse' or 'TaskSynapse' definitions"
echo "  - Monitor Discord #miners for breaking changes"
echo "  - Review recent commits in official repos"
echo ""

