#!/bin/bash
# Script to check official Autoppia GitHub repos for updates
# Helps identify if we're missing any required components

echo "🔍 Checking Official Autoppia GitHub Repositories"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

REPO_SUBNET="https://github.com/autoppia/autoppia_web_agents_subnet"
REPO_IWA="https://github.com/autoppia/autoppia_iwa"

echo "📦 Repository 1: Autoppia Web Agents Subnet"
echo "   ${REPO_SUBNET}"
echo ""
echo "   Key files to check:"
echo "   - protocol.py (synapse definitions)"
echo "   - miners/ (miner examples)"
echo "   - validators/ (validator code - shows what they expect)"
echo ""

echo "📦 Repository 2: Autoppia IWA Module"
echo "   ${REPO_IWA}"
echo ""
echo "   Key files to check:"
echo "   - ApifiedWebAgent implementation"
echo "   - Task format definitions"
echo "   - Action format specifications"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 What to Look For:"
echo ""
echo "1. ${GREEN}Synapse Types${NC}:"
echo "   - StartRoundSynapse definition"
echo "   - TaskSynapse definition"
echo "   - Any other required synapse types"
echo ""
echo "2. ${GREEN}Miner Patterns${NC}:"
echo "   - How official miners handle synapses"
echo "   - Axon setup patterns"
echo "   - API integration methods"
echo ""
echo "3. ${GREEN}Protocol Changes${NC}:"
echo "   - Recent commits affecting protocol"
echo "   - Breaking changes"
echo "   - New requirements"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Manual Check Steps:"
echo ""
echo "1. Visit: ${REPO_SUBNET}"
echo "2. Look for 'protocol.py' or 'synapse.py' files"
echo "3. Check 'miners/' directory for examples"
echo "4. Review recent commits for changes"
echo "5. Check README for setup instructions"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 Quick Links:"
echo ""
echo "Open repositories:"
echo "  xdg-open ${REPO_SUBNET} 2>/dev/null || open ${REPO_SUBNET} 2>/dev/null || echo 'Open: ${REPO_SUBNET}'"
echo "  xdg-open ${REPO_IWA} 2>/dev/null || open ${REPO_IWA} 2>/dev/null || echo 'Open: ${REPO_IWA}'"
echo ""
echo "Search for synapse types:"
echo "  Visit: ${REPO_SUBNET}/search?q=StartRoundSynapse"
echo "  Visit: ${REPO_SUBNET}/search?q=TaskSynapse"
echo ""

